= ターミナルやコマンドラインの使い方

ターミナルから文字を入力して，プログラムや命令を実行していく方法を学ぶ．

ターミナルは，アプリとして開く．あるいは，VS Codeなら，画面の下の部分にターミナルがある．

ポイントは，ターミナルでは，いま現在どこのフォルダ（ディレクトリともいう）にいるのか，を
意識する必要があるということ．

== 準備

ファイル名の拡張子(.pyや， .pyxresなど)，ピリオドから始まるファイル名の最後についている部分) を隠さないで表示するように
しておくこと．

== 覚えておきたいターミナルで使える命令や，キー操作

* `cd` : フォルダを指定すると，そのフォルダに移動する．
実行したいプログラムのあるフォルダに移動するのにつかう．
（フォルダを指定しないと，デフォルトのフォルダに移動してしまう．）

* `ls` : フォルダに入っているファイルを表示する．

* `pwd` : 今どこのフォルダにいるかを表示する．

* 上と下の矢印のキー．以前に実行した命令を選択する．繰り返し同じ命令を実行したいときに便利．

* タブキー： 命令を途中まで書いて押すと，残りを補完してくれる．

== pyxelを使ったプログラムの実行方法

いま，フォルダ `/Users/depenglab/Documents` に，実行したいプログラム `test.py` が置いてあるとする．

* ターミナルを開く．あるいは，VS Codeなら，画面の下の部分にターミナルがある．

* 開いたターミナルの現在のフォルダを，実行したいプログラムを置いているフォルダにする．
----
cd /Users/depenglab/Documents
----
注．Macなら，フォルダ名はうちこまなくても，Finderからドロップしてもよい．

* ターミナルから以下を実行．

----
pyxel run test.py
----

== pyxel editorの実行方法

実行したいプログラムのフォルダに移動してから，以下を実行．

----
pyxel edit mydata.pyxres
----

これで，Pyxel Editorが起動し，指定したファイル(上ではmydata.pyxres)が開かれる．

ファイル名を指定しないと， `my_resource.pyxres` という名前のファイルが開かれる． 


