= ターミナル(コマンドプロンプト)の使い方


ターミナル(Terminal) やコマンドプロンプトでは，文字で必要な命令を記述して実行する．

ポイントは，ターミナルでは，いま現在どこのフォルダ（ディレクトリともいう）にいるのか，を
意識する必要があるということ．

== 準備

ファイル名の拡張子(.pyや， .pyxresなど)，ピリオドから始まるファイル名の最後についている部分) を隠さないで表示するように
しておくこと．

== 覚えておきたいターミナルで使える命令や，キー操作

* `cd` : フォルダを指定すると，そのフォルダに移動する．
実行したいプログラムのあるフォルダに移動するのにつかう．
（フォルダを指定しないと，デフォルトのフォルダに移動してしまう．）

* `ls` : フォルダに入っているファイルを表示する．

* `pwd` : 今どこのフォルダにいるかを表示する．

* 上と下の矢印のキー．以前に実行した命令を選択する．繰り返し同じ命令を実行したいときに便利．

* タブキー： 命令を途中まで書いて押すと，残りを補完してくれる．

なお，`.` は現在のフォルダ，`..` は一つ上のフォルダを表す．
たとえば，タブを押したときに， `./test.py` や，`.\test.py` のように表示されたら，
それは，現在のフォルダにある `test.py` というファイルを表している．

== ターミナルから，pyxel editorを動かす方法

作られるキャラや音楽のデータがはいったファイルは，プログラムと同じ
フォルダに置いておくとよい．したがって，pyxel editorも，同じフォルダで実行した方がよい．

いま，フォルダ `/Users/depenglab/Documents` に，実行したいプログラム `test.py` が置いてあるとする．

* Terminal を開く．

* 開いたTerminal の現在のフォルダを，実行したいプログラムを置いているフォルダにする．
----
cd /Users/depenglab/Documents
----
注．フォルダ名は，うちこまなくても，
Finderからドロップしてもよい．

pyxel editorを起動する．Terminalから以下を実行． 
----
pyxel edit nanka_tekitona_name.pyxres
----

うまくいかない場合は，以下をためす，
----
python -m pyxel edit nanka_tekitona_name.pyxres
----


== ターミナルから，pyxelを使ったプログラムを実行する方法

いま，フォルダ `/Users/depenglab/Documents` に，実行したいプログラム `test.py` が置いてあるとする．

* ターミナルを開く．あるいは，VS Codeなら，画面の下の部分にターミナルがある．

* 開いたターミナルの現在のフォルダを，実行したいプログラムを置いているフォルダにする．
----
cd /Users/depenglab/Documents
----
注．Macなら，フォルダ名はうちこまなくても，Finderからドロップしてもよい．

* ターミナルから以下を実行．

----
python test.py
----

以下のようにしてもよい．
----
pyxel run test.py
----

== pyxel editorの実行方法

実行したいプログラムのフォルダに移動してから，以下を実行．

----
pyxel edit mydata.pyxres
----

これで，Pyxel Editorが起動し，指定したファイル(上ではmydata.pyxres)が開かれる．

ファイル名を指定しないと， `my_resource.pyxres` という名前のファイルが開かれる． 



