= 学問への扉：計算機プログラミング入門
// Pyxelプログラミング: レトロゲームで学ぶPython

==  はじめに

=== Python?

この授業では，Pythonという名前のプログラミング言語（プログラムを記述するための言語）をつかって，プログラムを作っていく．
まずは，各自のPCでPythonが使えるようにしよう．


https://www.python.jp/[Pythonのページ]のPython環境構築ガイドから，
自分のPCにあったものをインストールすればよい．
いくつか方法が記載されているので，推奨されている方法を選択するのをおすすめする．

Windowsの場合，ファイルの拡張子が表示されるようにしておこう．

=== プログラミングとは

==== Hello World!

最初のプログラムでは，Hello World!を表示させるのが定番．まずは，次のプログラムを実行しよう．

////

最初のプログラムは，Hello World!を表示させるものと決まっています．まずは，次のプログラムを実行してみましょう．

まず，エディタを起動して，プログラムを書きます．エディタは文字だけからなるデータを編集するためのツールで，Windowsならメモ帳，Macなら．．といったソフトウェアが相当します．打ち終えたらファイルとして保存しましょう．ここでファイル名は`hoge.py`としておきます．


次に，ターミナルという，直接文字を入力してコンピュータに様々な処理をさせたり，処理された結果を文字として表示するためのツールを起動します．
////

.手順
* IDLEという簡易的な統合開発環境がインストールされていると思うので，それを起動
* FileメニューからNew Fileを選択．エディタが現れるので，プログラムを入力．
* 名前を付けて保存．保存場所として，どこか分かりやすい場所に，フォルダをつくっておくとよい．
* エディタの方のRunメニューから，run moduleを選ぶと，プログラムが実行される

.hello.py
[source,python]
----
print("Hello world!")
----

////
.hello.py
[source,python]
----
include::sources/hello.py[lines=1..1]
----
////


==== セルシウス度とファーレンハイト度

セルシウス度からファーレンハイト度への変化を考える．
-273.15度より低い温度は存在しないので，無視しよう．
条件が成り立つときだけ実行したい処理は，ifを使って書く．
この処理の部分は，半角スペースで4文字下げること．


.temparature.py
[source,python]
----
# セルシウス度->ファーレンハイト度
print("温度を入力してください")
x = input()
x = float(x)
print("セルシウス度:", x)
if x >= -273.15:
    y = 1.8*x + 32
    print("ファーレンハイト度:", y)
----

-273.15度より低い値が入力されたとき，何かメッセージを出すように，プログラムを拡張しよう．
条件が成り立たない処理も書きたいときは，if-elseをつかえばよい．

.temparature.py
[source,python]
----
# セルシウス度->ファーレンハイト度
print("温度を入力してください")
x = input()
x = float(x)
print("セルシウス度:", x)
if x >= -273.15:
    y = 1.8*x + 32
    print("ファーレンハイト度:", y)
else:
    print("温度が低すぎます")
----

温度の対応表を出力してみる．
いろいろな対象に対して，処理を繰り替えす `for` がつかえる．

.temparature2.py
[source,python]
----
# セルシウス度->ファーレンハイト度
for i in range(-5, 40):
    print(i, "->", 1.8*i + 32)
----

`range(-5,40)` は-5, -4, ..., 39をあらわす．
 `i` にそれぞれの値を入れて，ループを繰り返す．
ループの部分は，4文字下げる．

==== 入れ子 (nesting)

ifやforなどの構造は，入れ子にできる．

.abc.py
[source,python]
----
# a, b, c どれが一番大きい？
print("a?")
a = int(input())
print("b?")
b = int(input())
print("c?")
c = int(input())

if a > b:
    if a > c:
        print(a)
    else:
        print(c)
else:
    if b > c:
        print(b)
    else:
        print(c)
----

=== 課題
FizzBuzzは，ひとりずつ１から順に数を数えていって，3で割り切れる場合は数ではなく「Fizz」，5で割り切れる場合は「Buzz」、両者で割り切れる場合は「Fizz-Buzz」と言うゲームである．これを，50までの数に対して行うプログラムをつくろう．

数のあまりは，%をつかって計算できる．たとえば，5 % 2 は 1．

2つの数が等しいかどうかは， == をつかって判定する．a == b は，aとbが同じ値なら True (真) となり，そうでなければ False (偽) となる．

.注意
* 行頭の空白には意味がある．その行がどこの階層にあるかを示している．
1つの階層を4つの半角の空白文字(スペース)であらわすこと．
* = は，左に右を代入するという意味．等号ではない！
等号は ==．不等号は !=．

==== ヒント
まずは，1から50までを表示．次に，3の倍数の時に「Fizz」を表示，というように，少しずつ改良していこう．

.fizz.py
[source,python]
----
for i in range(1,51):
    if i % 3 == 0:
        print("Fizz")
    else:
        print(i)
----

=== 発展課題
下のプログラムを入力して動かしてみよう．
ソースコードを読んで，何をしているか考えてみよう．

.guess.py
[source,python]
----
# これは数あてゲームです
import random

number = random.randint(1, 20)

print('この数は，1から20までの整数です')

for i in range(5):
    print('数をあててみて？')
    guess = input()
    guess = int(guess)

    if guess < number:
        print('小さすぎ')
    elif guess > number:
        print('大きすぎ')
    else:
        break

if guess == number:
    print('あたり！ トライした回数は' + str(i+1) + '回でした')
else:
    print('残念: 答えは' + str(number) + 'でした')
----
////
----
include::sources/guess.py[]
----
////
