= 学問への扉：計算機プログラミング入門

=== 前々回課題の回答例

////
.fizzbuzz1.py
[source,python]
----
include::sources/fizzbuzz1.py[lines=1..]
----
////

.fizzbuzz1.py
[source,python]
----
for i in range(1, 51):
    if i % 15 == 0:
        print("Fizz-Buzz")
    else:
        if i % 5 == 0:
            print("Buzz")
        else:
            if i % 3 == 0:
                print("Fizz")
            else:
                print(i)
----

////
.fizzbuzz2.py
[source,python]
----
include::sources/fizzbuzz2.py[lines=1..]
----
////

`if-elif-else` をつかった場合．

.fizzbuzz2.py
[source,python]
----
for i in range(1, 51):
    if i % 15 == 0:
        print("Fizz-Buzz")
    elif i % 5 == 0:
        print("Buzz")
    elif i % 3 == 0:
        print("Fizz")
    else:
        print(i)
----

=== 前回課題の回答例
変数 `awin`, `bwin` で，勝った回数を記録．

////
.janken2.py
[source,python]
----
include::sources/janken2.py[lines=1..]
----
////

.janken2.py
[source,python]
----
import random
JAN = ('グー', 'チョキ', 'パー')

awin = 0
bwin = 0
while awin < 3 and bwin < 3:
    a = random.randint(0,2)
    b = ""
    while b != '0' and b != '1' and b != '2':
        print(0, JAN[0], 1, JAN[1], 2, JAN[2], '?')
        b = input()
    b = int(b) # 入力を整数に変換
    print('こちら', JAN[b])
    print('あいて', JAN[a])

    if a == b:
        print('あいこ')
    elif (a == 0 and b == 1) or (a == 1 and b == 2) or (a == 2 and b == 0):
        print('まけ :-(')
        awin = awin + 1
        print('あいて: ', awin, ' こちら: ', bwin)
    else:
        print('かち :-)')
        bwin = bwin + 1
        print('あいて: ', awin, ' こちら: ', bwin)
----

`while` の条件は `True` のままで，ループを `break`
 する(ループを抜ける)ようにしてもよい．

== 関数 (function)
関数(function)は，共通のプログラムをまとめた，プログラムの部品．
`def function_name():` で，宣言することができる．
関数の名前を書くことで呼び出す (call)．

以降，`>>>` という記号が行頭にある場合は，REPL (Read-Eval-Print Loop)
というインタラクティブモードでの実行の様子をあらわす．
この環境だと，プログラムを書いて保存して実行するのではなく，
命令を入力すると，その都度実行され結果が表示される．

IDLEのPython Shell で，REPLが使える．
あるいは，MacのターミナルとWinのコマンドプロンプトで，それぞれ
`python3` `python` と打ち込んでEnterをおす．

----
>>> def factorial(n):
	result = 1
	for i in range(2, n+1):
		result = result * i
	return result

>>> factorial(1)
1
>>> factorial(10)
3628800
>>> factorial(3)
6
----

じゃんけんのプログラムの一部を関数にしてみる．

////
.janken3.py
[source,python]
----
include::sources/janken3.py[lines=1..]
----
////

.janken3.py
[source,python]
----
import random
JAN = ('グー', 'チョキ', 'パー')

awin = 0
bwin = 0

def show_wins():
    print('あいて: ', awin, ' こちら: ', bwin)

while awin < 3 and bwin < 3:
    a = random.randint(0,2)
    b = ""
    while b != '0' and b != '1' and b != '2':
        print(0, JAN[0], 1, JAN[1], 2, JAN[2], '?')
        b = input()
    b = int(b) # 入力を整数に変換
    print('こちら', JAN[b])
    print('あいて', JAN[a])

    if a == b:
        print('あいこ')
    elif (a == 0 and b == 1) or (a == 1 and b == 2) or (a == 2 and b == 0):
        print('まけ :-(')
        awin = awin + 1
        show_wins()
    else:
        print('かち :-)')
        bwin = bwin + 1
        show_wins()
----


また，関数は引数(ひきすう, parameter)として入力を受け取ったり，
結果を返したりすることができる．`return` を実行すると，
このキーワードの後に指定されている返り値 (戻り値, return value)を返して，関数から抜ける．

次のプログラムは，何をやっているのだろう？

////
.reverse.py
[source,python]
----
include::sources/reverse.py[lines=1..]
----
////

.reverse.py
[source,python]
----
def reverse(str):
    res = ""
    for c in str:
        res = c + res
    return res

s = input()
print(reverse(s))
----


////
==== 再帰プログラム recursive program
自分で自分をよびだすプログラム．動かかして，動作を理解しよう．
////

////
.reverse2.py
[source,python]
----
include::sources/reverse2.py[lines=1..]
----
////

////
.reverse2.py
[source,python]
----
def reverse(str):
    if str == "":
        return ""
    return reverse(str[1:]) + str[0]

s = input()
print(reverse(s))
----
////

=== Hangman

Hangman(相手の考えた単語を当てる2人用のゲーム)のプログラムをつくっていこう．
関数を一つずつつくって，最後にそれらをつかってプログラムを完成させる．

（以下では，REPLでの実行の様子を示すことで，それぞれの関数について説明．
実際には，すべての関数を1つのファイルに書いてプログラムを作る．）

単語をランダムに選択．

----
>>> import random
>>> def get_word():
    WORDS = "turaco shoebill tropicbird eagle crane peafowl dove \
            hummingbird puffin cassowary lorikeet flamingo penguin \
            heron booby owl toucan".split()
    index = random.randint(0, len(WORDS)-1)
    return WORDS[index]

>>> get_word()
'flamingo'
>>> get_word()
'heron'
----

単語を，指定された文字の部分だけ表示．
////
なお，`for` についている `else` の部分は，`break` が起らなかった場合にのみ実行される．
////

----
>>> def unmask_word(word, letters):
    st = ""
    for c in word:
        tmp = "_"
        for l in letters:
            if c == l:
                tmp = c
        st = st + tmp
    return st

>>> unmask_word("python", "opqr")
'p___o_'
----

英小文字を1字入力するまでループ．

----
>>> def input_letter():
    while True:
        print("英文字を1字入力")
        st = input()
        if len(st) == 1 and st in 'abcdefghijklmnopqrstuvwxyz':
            return st


>>> input_letter()
英文字を1字入力
ab
英文字を1字入力
B
英文字を1字入力
z
'z'
----

正解かどうかを判定．

----
>>> def is_correct(secretword, letters):
    for c in secretword:
        is_covered = False
        for l in letters:
            if c == l:
                is_covered = True
        if is_covered == False:
            return False
    return True


>>> is_correct("python", "nohhhtyp")
True
>>> is_correct("python", "python")
True
>>> is_correct("python", "thon")
False
----

=== 課題1
これらを使ってプログラムを完成させよう．
これらの関数のあとに，次のコードを追加したプログラムを書いて，動かしてみよう．

[source,python]
----
inputLetters = ""
secret = get_word()
st = unmask_word(secret, inputLetters)
print(st)
while is_correct(secret, inputLetters) == False:
    inputLetters = inputLetters + input_letter()
    st = unmask_word(secret, inputLetters)
    print(st)
----

=== 課題2
入力することのできる回数を設定しよう．
さらに，間違える度に，ライフが減っていくのが分かるようにしてみよう．

=== 発展課題
アスキーアートで，元のゲームを再現してみよう．
改行を含んだ文字列を，''' で挟むことで指定できる．
----
>>> PIC1 = '''
 +---+
     |
     |
     |
    ==='''
>>> print(PIC1)

 +---+
     |
     |
     |
    ===
>>>
----
