= 学問への扉：計算機プログラミング入門

== 関数 (function) つづき
関数はプログラムの部品のこと．

=== おさらい
つぎの関数はなにをしているのだろう．
中身をちゃんと理解しよう．

注意．下はPython ShellなどのREPL（対話的なプログラム実行環境のこと）での実行の様子．
たとえば， `>>>` は，入力待ち状態であることを表す記号．
[source,python]
----
>>> def test_primality(n):
	if n <= 1:
		return False
	for i in range(2,n):
		if n % i == 0:
			return False
	return True

>>> test_primality(1)
False
>>> test_primality(2)
True
>>> test_primality(3)
True
>>> test_primality(4)
False
----

`n` は仮引数（かりひきすう, parameter），
`2`　や `5` は実引数 (じつひきすう, argument)．
関数は，仮引数が実引数に置き換えられて，実行される．

////
`else` の部分は `for` が `break` されなかったときに実行される．
（ `for-else` ． `if-else` ではない．）
////

=== 変数のスコープ (scope)

二つのプログラム．出力は同じか，違うか？

////
.globallocal1.py
[source,python]
----
include::sources/globallocal1.py[lines=1..]
----
////

.globallocal1.py
[source,python]
----
def f(x):
    a = x

a = 10
print(a)
f(100)
print(a)
----


関数内で利用される変数は，その関数だけで有効．同じ名前でも，区別される．
変数が有効な範囲をスコープとよぶ．

////
.globallocal2.py
[source,python]
----
include::sources/globallocal2.py[lines=1..]
----
////


.globallocal2.py
[source,python]
----
def f(x):
    global a
    a = x

a = 10
print(a)
f(100)
print(a)
----

関数の外で定義されている変数（グローバル変数）を関数内で使用する場合は，
`global` をつかって変数を指定．


== リスト (list)

データの列を保存するしくみ．
オフセット (offset)を指定して，要素にアクセスする．
（注．Python以外では，添え字(そえじ, index)と呼ぶことが多い．）


[source,python]
----
>>> weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
>>> weekdays[0]
'Monday'
>>> weekdays[4]
'Friday'
>>> weekdays[-1]
'Friday'
>>> weekdays[-5]
'Monday'
----
’append()' で追加．
'extend()' で，別のリストを追加．

[source,python]
----
>>> weekend = ['Saturday']
>>> weekend.append('Sunday')
>>> weekend
['Saturday', 'Sunday']
>>> weekdays.extend(weekend)
>>> weekdays
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
----
その他，リスト途中への要素の追加や，削除など，いろいろな機能が存在．

`len` で，リストの長さを取得．
[source,python]
----
>>> len(weekdays)
7
----

リストのそれぞれの要素に対して，処理を実行．
[source,python]
----
>>> for day in weekdays:
	print(day)

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
----


== Hangman つづき
==== 前回のプログラムの原型全体

関数 `get_word()` の `WORD` は，単語のリストになっている．
(`split()` で，文字列を単語に分割して，リストにしている．)

////
.hangman.py
[source,python]
----
include::sources/hangman.py[lines=1..]
----
////

.hangman.py
[source,python]
----
# hangman
import random
def get_word():
    WORDS = "turaco shoebill tropicbird eagle crane peafowl dove \
            hummingbird puffin cassowary lorikeet flamingo penguin \
            heron booby owl toucan".split()
    offset = random.randint(0, len(WORDS)-1)
    return WORDS[offset]

def unmask_word(word, letters):
    st = ""
    for c in word:
        for l in letters:
            if c == l:
                st = st + c
                break
        else:
            st = st + "_"
    return st

def is_correct(secretword, letters):
    for c in secretword:
        for l in letters:
            if c == l:
                break
        else:
            return False
    return True

def input_letter():
    while True:
        print("英文字を1字入力")
        st = input()
        st = st.lower()
        if len(st) == 1:
            if st in 'abcdefghijklmnopqrstuvwxyz':
                break
    return st

life = 5
inputLetters = ""
secret = get_word()
st = unmask_word(secret, inputLetters)
print("life:", life)
print(st)
while is_correct(secret, inputLetters) == False:
    inputLetters = inputLetters + input_letter()
    st_next = unmask_word(secret, inputLetters)
    print(st_next)
    if st == st_next:
        life = life - 1
        print("life:", life)
        if life <= 0:
             break
    st = st_next
----

=== 課題
少し拡張したHangmanを完成させよう．
CLEから投稿．

==== 次回以降について

https://github.com/kitao/pyxel/blob/master/README.ja.md[pyxel] をつかって，
プログラムを作っていく予定．
自分のPCを使っている人は，インストールしよう．

時間が余っている人は，少し動かしてみること．
////
.pyxel_test.py
[source,python]
----
include::sources/pyxel_test.py[lines=1..]
----
////

.pyxel_test.py
[source,python]
----
import pyxel

pyxel.init(160, 120)

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)
    pyxel.rect(10, 10, 20, 20, 11)

pyxel.run(update, draw)
----

Qで終了．
